export const DEAD_DOMAINS = new Set(
  [
    'netscape.net',
    'prodigy.net',
    'prodigy.com',
    'webtv.net',
    'wmconnect.com',
    'excite.com',
    'mailexcite.com',
    'juno.com',
    'worldnet.att.net',
    'collegeclub.com',
    'address.com',
    'dodgeit.com',
    'lovetestclub.com',
    'goennounce.com',
    'angelfire.com',
    'altavista.com',
    'blackplanet.com',
    'iwon.com',
    'lycos.com',
    'myway.com',
    'go.com',
    'adelphia.net',
    'adelphia.com',
    'attbi.com',
  ].map((d) => d.toLowerCase()),
);

export const CONSUMER_DOMAINS = new Set(
  [
    'gmail.com',
    'yahoo.com',
    'yahoo.es',
    'ymail.com',
    'hotmail.com',
    'hotmail.co.uk',
    'aol.com',
    'aol.ocm',
    'msn.com',
    'live.com',
    'outlook.com',
    'icloud.com',
    'me.com',
    'mac.com',
    'comcast.net',
    'comcast.com',
    'att.net',
    'att.com',
    'bellsouth.net',
    'bellsouth.com',
    'sbcglobal.net',
    'verizon.net',
    'verizonwireless.com',
    'earthlink.net',
    'mindspring.com',
    'cox.net',
    'charter.net',
    'roadrunner.com',
    'tampabay.rr.com',
    'cfl.rr.com',
    'twcny.rr.com',
    'nc.rr.com',
    'rochester.rr.com',
    'austin.rr.com',
    'cinci.rr.com',
    'nycap.rr.com',
    'triad.rr.com',
    'pacbell.net',
    'ameritech.net',
    'qwest.net',
    'qwestoffice.net',
    'windstream.net',
    'frontier.com',
    'frontiernet.net',
    'centurylink.net',
    'tds.net',
    'alltel.net',
    'allwest.net',
    'wildblue.net',
    'wildblue.ne',
    'cableone.net',
    'epix.net',
    '3rivers.net',
    'zoominternet.net',
    'wowway.com',
    'optonline.net',
    'mediaone.net',
    'mchsi.com',
    'attglobal.net',
    'embarqmail.com',
    'ptd.net',
    'netzero.net',
    'netzero.com',
    'cs.com',
    'mail.com',
    'gmx.com',
    'inbox.com',
    'aim.com',
    'usa.net',
    'hitter.net',
    'gte.net',
    'ubtanet.com',
    'concentric.net',
    'execpc.com',
    'inet-1.com',
    'supanet.com',
    'peganet.com',
    'gci.net',
    'dishmail.net',
    'fi.com',
    'itsnet.com',
    'mpoweryou.net',
    'ihavenet.com',
    'intellistar.net',
    'tivo.com',
    'zebra.net',
    'q.com',
    'flash.net',
    'fla.com',
    'htn.net',
    'cpaz.net',
    'dncs.net',
    'cfi.net',
    'wfrmls.com',
  ].map((d) => d.toLowerCase()),
);

export const ROLE_PREFIXES = [
  'info',
  'office',
  'admin',
  'sales',
  'contact',
  'support',
  'hello',
  'mail',
  'noreply',
  'no-reply',
  'webmaster',
  'billing',
  'help',
  'team',
  'service',
  'enquiries',
  'enquiry',
  'inquiry',
  'general',
  'reception',
  'accounts',
  'operations',
] as const;

export function isDeadDomain(domain: string): boolean {
  return DEAD_DOMAINS.has(domain.toLowerCase());
}

export function isConsumerDomain(domain: string): boolean {
  return CONSUMER_DOMAINS.has(domain.toLowerCase());
}

export function isBusinessDomain(domain: string): boolean {
  const normalized = domain.toLowerCase();
  return !DEAD_DOMAINS.has(normalized) && !CONSUMER_DOMAINS.has(normalized);
}
