import { CAMPAIGN_FLOW_EXAMPLE_LINEAR } from '../../campaigns/flow/index.js';
import {
  BULK_ASYNC_LIMIT,
  BULK_SYNC_LIMIT,
  MAX_ASYNC_JOBS_PER_ACCOUNT,
} from './constants.js';
import type { DocLinkMode } from './docLinks.js';
import { guideLink, referenceLink } from './docLinks.js';

const EXAMPLE_CAMPAIGN_ID = '1d8dc901-3d2d-4d9f-9dcc-4f8b3aa1a1fb';
const EXAMPLE_MAILBOX_ID = 'c23da7b6-df4e-4d2f-b100-4bb07b7d38d7';
const EXAMPLE_LEAD_ID = 'f2a1b9c4-8e7d-4a3b-9c1e-2d5f6a7b8c9d';
const EXAMPLE_THREAD_ID = 'b7e2c1a4-3f5d-4e8a-9b0c-1d2e3f4a5b6c';
const EXAMPLE_MESSAGE_JOB_ID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';
const EXAMPLE_JOB_ID = '9f8e7d6c-5b4a-3210-9876-543210fedcba';
const EXAMPLE_GLOBAL_LEAD_ID = 'sha256:example-person-id';

function jsonExample(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

/** Get Started: minimal first-request quickstart. No sequence/lifecycle detail. */
export function buildCampaignQuickstartMarkdown(linkMode: DocLinkMode = 'openapi'): string {
  return [
    'This gets you from an API key to your first successful request in a couple of minutes.',
    '',
    '## Before you start',
    '',
    `- An API key. Create one in Furnace under **Account Settings \u2192 API keys** and send it as \`Authorization: Bearer f_...\` (see ${guideLink('Authentication', '/guides/authentication/', linkMode)}).`,
    '- At least one connected mailbox to send from.',
    '',
    '## 1. Make your first request',
    '',
    'List the inboxes connected to your account:',
    '',
    '```bash',
    `curl -sS 'https://api.getfurnace.io/v1/mailboxes' \\`,
    `  -H 'Authorization: Bearer f_your_key_here'`,
    '```',
    '',
    'You get back your mailboxes and their ids. Keep one id handy \u2014 a campaign sends from it.',
    '',
    '## 2. Create a draft campaign',
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/campaigns' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    `  -d '${jsonExample({ name: 'My first campaign' })}'`,
    '```',
    '',
    'This returns a campaign with `status: draft`. Nothing sends until you launch it.',
    '',
    '## Next',
    '',
    `You now have an empty draft. Add an email sequence, add people, and launch it in the ${guideLink('Campaign setup', '/guides/campaign-setup/', linkMode)} guide.`,
  ].join('\n');
}

/** Guide: build and launch a campaign end to end (the full curl walkthrough). */
export function buildCampaignSetupMarkdown(linkMode: DocLinkMode = 'openapi'): string {
  return [
    `Build and launch a real campaign end to end. New here? Read ${guideLink('Campaigns', '/concepts/campaigns/', linkMode)} and ${guideLink('Email sequences', '/concepts/sequences/', linkMode)} first.`,
    '',
    'Replace `f_your_key_here` with your API key and the example ids with your own.',
    '',
    '## 1. Pick a mailbox',
    '',
    'List your inboxes and copy a mailbox id to send from:',
    '',
    '```bash',
    `curl -sS 'https://api.getfurnace.io/v1/mailboxes' \\`,
    `  -H 'Authorization: Bearer f_your_key_here'`,
    '```',
    '',
    '## 2. Create a draft campaign',
    '',
    'Give it a name and the mailbox it sends from:',
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/campaigns' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample({
      name: 'Q2 Outbound',
      mailbox_ids: [EXAMPLE_MAILBOX_ID],
    }),
    '\'',
    '```',
    '',
    'The response includes the new campaign\u2019s `id`. Use it in the next steps.',
    '',
    '## 3. Add your email sequence',
    '',
    'Send the steps people will move through. This example sends an email, waits, then sends a follow-up:',
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/flow' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample(CAMPAIGN_FLOW_EXAMPLE_LINEAR),
    '\'',
    '```',
    '',
    `The copy uses tokens like \`{{first_name}}\` and \`{{custom.company}}\`. Any \`{{custom.*}}\` token becomes a value you provide for each person in the next step. See ${guideLink('Email sequences', '/concepts/sequences/', linkMode)}.`,
    '',
    '## 4. Add a person',
    '',
    'Add someone to the campaign. Include any custom fields the sequence uses:',
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/leads' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample({
      email: 'alex@acme.com',
      first_name: 'Alex',
      last_name: 'Rivera',
      custom_lead_data: { company: 'Acme Corp' },
    }),
    '\'',
    '```',
    '',
    `Adding more people, updating, or importing in bulk is covered in ${guideLink('Lead management', '/guides/lead-management/', linkMode)}.`,
    '',
    '## 5. Launch',
    '',
    'Start sending. This puts everyone you added into the sequence:',
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/launch' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'{}\'',
    '```',
    '',
    'The campaign is now `running`.',
    '',
    '## Editing after launch',
    '',
    '| While the campaign is | You can | You cannot |',
    '| --- | --- | --- |',
    '| **draft** | Change anything | \u2014 |',
    '| **running** | Edit email copy and timing | Add, remove, or reorder steps |',
    '| **paused** | Change anything, then resume | \u2014 |',
    '| **stopped** | \u2014 | Edit anything |',
    '',
    'To add, remove, or reorder steps on a live campaign, pause it first, make the change, then resume. If you try a structural change while running, the request is rejected with a message telling you to pause.',
    '',
    `Pause, resume, and stop through the campaign status endpoint \u2014 see the ${referenceLink('API Reference', '/reference/', linkMode)}.`,
  ].join('\n');
}

/** Guide: add and manage the people in a campaign. */
export function buildLeadManagementMarkdown(linkMode: DocLinkMode = 'openapi'): string {
  return [
    'By the end of this guide you can add people to a campaign, fix missing personalization fields, import a list (sync or async), and move existing people between campaigns.',
    '',
    `A person added to a campaign is a **lead** in that campaign. Read ${guideLink('Leads and people', '/concepts/leads-people/', linkMode)} first if those words are new.`,
    '',
    'Replace `f_your_key_here` and the example ids with your own.',
    '',
    '## Before you start',
    '',
    `- A campaign with an email sequence. The ${guideLink('Campaign setup', '/guides/campaign-setup/', linkMode)} guide builds one.`,
    '- If the sequence uses custom fields (for example `{{custom.company}}`), every person you add must include those keys in `custom_lead_data` or the request is rejected / the lead is marked incomplete.',
    '',
    '## 1. Add one person',
    '',
    'Include every custom field the sequence requires:',
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/leads' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample({
      email: 'alex@acme.com',
      first_name: 'Alex',
      last_name: 'Rivera',
      custom_lead_data: { company: 'Acme Corp' },
    }),
    '\'',
    '```',
    '',
    '**Success:** the response includes the lead `id` and the person\'s `global_lead_id`. If the campaign is already running, they enter the sequence when enrollment succeeds.',
    '',
    '## 2. Fix or remove a person',
    '',
    'Update fields (for example a missing company name) with `PATCH`:',
    '',
    '```bash',
    `curl -sS -X PATCH 'https://api.getfurnace.io/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/leads/${EXAMPLE_LEAD_ID}' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    `  -d '${jsonExample({
      first_name: 'Alexandra',
      custom_lead_data: { company: 'Acme Corp' },
    })}'`,
    '```',
    '',
    'Remove them from **this** campaign only:',
    '',
    '```bash',
    `curl -sS -X DELETE 'https://api.getfurnace.io/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/leads/${EXAMPLE_LEAD_ID}' \\`,
    `  -H 'Authorization: Bearer f_your_key_here'`,
    '```',
    '',
    'That does not delete the underlying person from your account. They stay available for other campaigns.',
    '',
    '## 3. Import a list (up to 100)',
    '',
    `Use sync bulk when the batch fits in one request (max ${BULK_SYNC_LIMIT} people):`,
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/leads/bulk' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample({
      leads: [
        {
          email: 'alex@acme.com',
          first_name: 'Alex',
          custom_lead_data: { company: 'Acme Corp' },
        },
        {
          email: 'sam@example.com',
          first_name: 'Sam',
          custom_lead_data: { company: 'Example Inc' },
        },
      ],
    }),
    '\'',
    '```',
    '',
    '**Success:** the response reports `imported`, `incomplete`, `failed`, and an `errors` array. `incomplete` means the lead was created but is missing required personalization fields — fix those with `PATCH` before you expect emails to send.',
    '',
    '## 4. Import a large list (async job)',
    '',
    `For bigger lists, queue a job (up to ${BULK_ASYNC_LIMIT} people per request, and up to ${MAX_ASYNC_JOBS_PER_ACCOUNT} jobs running at once):`,
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/leads/bulk/async' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample({
      leads: [
        {
          email: 'alex@acme.com',
          first_name: 'Alex',
          custom_lead_data: { company: 'Acme Corp' },
        },
      ],
    }),
    '\'',
    '```',
    '',
    'Poll until the job finishes:',
    '',
    '```bash',
    `curl -sS 'https://api.getfurnace.io/v1/jobs/${EXAMPLE_JOB_ID}' \\`,
    `  -H 'Authorization: Bearer f_your_key_here'`,
    '```',
    '',
    '**Success:** `status` is `completed` (or `failed`). Counts live in `result` (`created`, `updated`, `incomplete`, `failed`, and so on). Prefer webhooks for completion if you already use them — see ' +
      guideLink('Webhook integration', '/guides/webhook-integration/', linkMode) +
      '.',
    '',
    '## 5. Move existing people between campaigns',
    '',
    'When people already exist in your account (you have their `global_lead_id`), add them to another campaign without re-posting full contact rows:',
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/leads:add' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    `  -d '${jsonExample({ global_lead_ids: [EXAMPLE_GLOBAL_LEAD_ID] })}'`,
    '```',
    '',
    'Remove them from a campaign with `POST /v1/campaigns/{id}/leads:remove`, or from every campaign with `POST /v1/leads:remove-from-all-campaigns`.',
    '',
    '**Success:** the response counts `created` / `enrolled` / `skipped` (add) or `removed` / `skipped` (remove).',
    '',
    '## Common mistakes',
    '',
    '| Symptom | Likely cause |',
    '| --- | --- |',
    '| Request rejected or lead incomplete | Missing a required `custom_lead_data` key from the sequence |',
    '| Person never receives email | Campaign still `draft` (launch it), no mailbox assigned, or enrollment paused |',
    '| Bulk import times out / too large | Use `/leads/bulk/async` and poll `GET /v1/jobs/{id}` |',
    '| DELETE removed them from one campaign only | Expected — the account person remains for other campaigns |',
    '',
    '## 6. Tags and email verification',
    '',
    'Tags are **account-level and person-keyed**. They describe the person (`global_lead_id`), not one campaign lead row. `custom_lead_data` stays per campaign.',
    '',
    'Pass `tags` as names or aliases. Furnace matches the built-in catalog case-insensitively (for example `Hunter.io` → Hunter, `GMB` → Google Maps) and find-or-creates an account-owned tag when nothing matches. Built-in catalog tags cannot be deleted.',
    '',
    '**Provider** (how you found them): Apollo, Hunter, Prospeo, Clay, Apify, Serper, Google Maps, LinkedIn Sales Navigator, Website Crawl, SkipSherpa, Meta Ad Library, LinkedIn Ad Library, Google Ads Transparency, Business Registry, License Roster, HubSpot, Salesforce, Client CSV, Webinar Registrant List, Demo Request, Content Download, Referral.',
    '',
    '**Signal** (why they are in the list): Running Meta Ads, Running Google Ads, Running LinkedIn Ads, Webinar Or Event Ad, Qualifying Ad Copy, Ads Paused, Hiring Intent, Recently Funded, Tech Match, Regulated Or Licensed, Verified Business, ICP Fit, Decision Maker, Owner Operator, Local Business, Engaged, Webinar Attendee, Webinar No Show.',
    '',
    '**Other** (operator filters): Catch-All Domain, Role Account, Needs Review, Do Not Send, Existing Customer, Open Opportunity, Previously Contacted, High Fit, Low Fit, EU Contact.',
    '',
    'If you already have MillionVerifier (or similar) output, send `email_verification` with `status` of `ok`, `catch_all`, `invalid`, `unknown`, or `disposable`. Do **not** auto-apply Catch-All Domain or Role Account tags from that payload — those tags are for operators who want them in filters. Omit `email_verification` unless you have a real check. Do not invent a status.',
    '',
    'Bulk and staged import use the same `LeadCreate` fields. Omitting them behaves as before.',
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/leads' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample({
      email: 'alex@acme.com',
      first_name: 'Alex',
      custom_lead_data: { company: 'Acme Corp' },
      tags: ['Hunter', 'ICP Fit'],
      email_verification: { status: 'ok', provider: 'millionverifier' },
    }),
    '\'',
    '```',
    '',
    '## Next',
    '',
    `- Read replies in ${guideLink('Handling replies', '/guides/handling-replies/', linkMode)}.`,
    `- Field-level detail is in the ${referenceLink('API Reference', '/reference/', linkMode)}.`,
  ].join('\n');
}

/** Guide: read replies and send responses from the inbox. */
export function buildHandlingRepliesMarkdown(linkMode: DocLinkMode = 'openapi'): string {
  return [
    'By the end of this guide you can find a reply, read the conversation, send a response, and track whether that response actually sent.',
    '',
    'When someone replies, Furnace groups the exchange into a **thread** on the campaign\'s mailbox.',
    '',
    'Replace `f_your_key_here` and the example ids with your own.',
    '',
    '## Before you start',
    '',
    '- A running campaign that has already sent mail (so replies can arrive).',
    '- An API key with access to the account inbox.',
    '',
    '## 1. List conversations',
    '',
    '```bash',
    `curl -sS 'https://api.getfurnace.io/v1/threads' \\`,
    `  -H 'Authorization: Bearer f_your_key_here'`,
    '```',
    '',
    'Filter and sort in the ' +
      referenceLink('API Reference', '/reference/', linkMode) +
      ' (for example by campaign or latest inbound activity). Copy a thread `id` for the next steps.',
    '',
    '**Success:** you get a page of threads. New replies typically show a recent `last_inbound_at`.',
    '',
    '## 2. Read the messages',
    '',
    '```bash',
    `curl -sS 'https://api.getfurnace.io/v1/threads/${EXAMPLE_THREAD_ID}/messages' \\`,
    `  -H 'Authorization: Bearer f_your_key_here'`,
    '```',
    '',
    '**Success:** messages include direction (`sent` / `received`), subject, and body fields you can display or pass to your own agent.',
    '',
    '## 3. Send a reply',
    '',
    'Sending is **queued**. The API returns a **message job**, not proof that the email left the mailbox yet.',
    '',
    '```bash',
    `curl -sS -X POST 'https://api.getfurnace.io/v1/threads/${EXAMPLE_THREAD_ID}/reply' \\`,
    `  -H 'Authorization: Bearer f_your_key_here' \\`,
    `  -H 'Content-Type: application/json' \\`,
    `  -d '${jsonExample({ body_html: '<p>Thanks Alex — how about Thursday?</p>' })}'`,
    '```',
    '',
    'Forward instead with `POST /v1/threads/{id}/forward` when you need to hand the thread off.',
    '',
    '**Success:** the response includes a message job `id`.',
    '',
    '## 4. Track the send',
    '',
    'Poll the job until it finishes:',
    '',
    '```bash',
    `curl -sS 'https://api.getfurnace.io/v1/message-jobs/${EXAMPLE_MESSAGE_JOB_ID}' \\`,
    `  -H 'Authorization: Bearer f_your_key_here'`,
    '```',
    '',
    'While it is still queued you can:',
    '',
    '```bash',
    `# Cancel`,
    `curl -sS -X POST 'https://api.getfurnace.io/v1/message-jobs/${EXAMPLE_MESSAGE_JOB_ID}/cancel' \\`,
    `  -H 'Authorization: Bearer f_your_key_here'`,
    '',
    `# Or send immediately`,
    `curl -sS -X POST 'https://api.getfurnace.io/v1/message-jobs/${EXAMPLE_MESSAGE_JOB_ID}/send-now' \\`,
    `  -H 'Authorization: Bearer f_your_key_here'`,
    '```',
    '',
    '**Success:** the job reaches a terminal status (sent or cancelled). Prefer `email.sent` webhooks if you do not want to poll.',
    '',
    '## 5. Organize the thread (optional)',
    '',
    'Typical triage actions:',
    '',
    '- **Categorize, mark read, or change status:** `PATCH /v1/threads/{id}`',
    '- **Set or clear out-of-office:** `POST /v1/threads/{id}/out-of-office`',
    '- **Add or remove tags:** `POST /v1/threads/{id}/tags:add` and `POST /v1/threads/{id}/tags:remove`',
    '',
    '## 6. Get notified when replies arrive',
    '',
    `Instead of polling threads, wire ${guideLink('Webhook integration', '/guides/webhook-integration/', linkMode)} and enable email-activity events such as \`reply.received\` and \`reply.categorized\`. Payload examples live under **Webhook events** in the sidebar.`,
    '',
    '## Common mistakes',
    '',
    '| Symptom | Likely cause |',
    '| --- | --- |',
    '| Reply endpoint returned but mail never sent | Message job still queued or failed — poll `GET /v1/message-jobs/{id}` |',
    '| Empty thread list | Wrong account key, or no inbound mail yet on those mailboxes |',
    '| Missing reply body in your app | Reading thread list only — load `…/messages` for bodies |',
    '',
    '## Next',
    '',
    `- Manage who is in the campaign with ${guideLink('Lead management', '/guides/lead-management/', linkMode)}.`,
    `- Every thread and message field is in the ${referenceLink('API Reference', '/reference/', linkMode)}.`,
  ].join('\n');
}

export {
  EXAMPLE_CAMPAIGN_ID,
  EXAMPLE_MAILBOX_ID,
};
