import {
  CAMPAIGN_FLOW_EXAMPLE_CATEGORIZER,
  CAMPAIGN_FLOW_EXAMPLE_LINEAR,
} from '../../campaigns/flow/index.js';
import { modelLink } from './docLinks.js';

const EXAMPLE_CAMPAIGN_ID = '1d8dc901-3d2d-4d9f-9dcc-4f8b3aa1a1fb';
const EXAMPLE_MAILBOX_ID = 'c23da7b6-df4e-4d2f-b100-4bb07b7d38d7';
const EXAMPLE_TAG_ID = 'a1b2c3d4-e5f6-4789-a012-3456789abcde';

function jsonExample(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

const FLOW_MODELS_LINK = `Models → ${modelLink('CampaignFlow')}`;

export function buildBuildingCampaignsMarkdown(): string {
  return [
    '## What is a campaign?',
    '',
    'A Furnace campaign is an outbound sequence for a set of leads: a **flow graph** (emails, waits, categorizer branches, webhooks), one or more **mailboxes**, an optional **schedule**, and **leads** imported before launch.',
    '',
    'Lifecycle: **draft** → `POST /launch` → **running** → `PATCH /status` for pause/resume/stop. While live, you may edit copy and node configuration but not structural topology (add/remove nodes or edges).',
    '',
    'Build campaigns through the API in four phases: create a **draft**, define the **flow**, upload **leads**, then **launch** the campaign.',
    '',
    `For the full flow object reference (every node type, field, merge variable, normalization rule, and validation code), open **${FLOW_MODELS_LINK}** and related schemas (${modelLink('FlowUpdate')}, ${modelLink('FlowValidationIssue')}).`,
    '',
    '## TL;DR — checklist',
    '',
    '1. `GET /v1/mailboxes` — pick real mailbox UUIDs (no default mailbox alias)',
    '2. `POST /v1/campaigns` — create draft; optional `flow`, `mailbox_ids`, `schedule`',
    '3. `POST /v1/campaigns/{id}/flow` — save flow; check `field_sync` in the response',
    '4. `POST /v1/campaigns/{id}/leads` — import leads',
    '5. `GET /v1/campaigns/{id}?include=launch_state,lead_field_state` — verify readiness',
    '6. `POST /v1/campaigns/{id}/launch` — enroll all leads and start',
    '',
    'After launch, use `PATCH /v1/campaigns/{id}/status` (not `/launch`) for pause/resume/stop.',
    '',
    '## field_sync',
    '',
    'When copy references merge variables, Furnace auto-declares fields on the lead source before validate/save. Every flow save response includes:',
    '',
    '```json',
    '{ "field_sync": { "declared_custom_added": ["company"], "declared_standard_added": [] } }',
    '```',
    '',
    'The response `flow` is truth — persisted `customFieldKeys` may differ from your request body.',
    '',
    '## If-Match / conflict recovery',
    '',
    '1. `GET /v1/campaigns/{id}/flow` (or campaign detail) → read `flow_revision`',
    '2. `POST /v1/campaigns/{id}/flow` with header `If-Match: <flow_revision>`',
    '3. On `412 flow_revision_conflict`, read `current_flow_revision` from the error body, refresh your base flow, merge manually, retry',
    '',
    '## TL;DR — four phases',
    '',
    '```mermaid',
    'flowchart LR',
    '  createDraft["POST /v1/campaigns"] --> saveFlow["POST .../flow"]',
    '  saveFlow --> uploadLeads["POST .../leads"]',
    '  uploadLeads --> launch["POST .../launch"]',
    '  launch --> live["status: running"]',
    '  live --> contentEdits["PUT .../flow content edits OK"]',
    '  live --> blocked["structural edits → flow_locked"]',
    '```',
    '',
    '| Phase | Endpoint | What happens |',
    '| --- | --- | --- |',
    '| 1. Create draft | `POST /v1/campaigns` | New campaign with `status: draft`. Optional initial flow, mailboxes, tags, schedule. |',
    '| 2. Save flow | `PUT /v1/campaigns/{id}/flow` | Furnace normalizes, validates, and persists the graph. |',
    '| 3. Upload leads | `POST /v1/campaigns/{id}/leads` or `.../leads/bulk` | Upsert leads; custom fields from the flow are required in `custom_lead_data`. |',
    '| 4. Launch | `POST /v1/campaigns/{id}/launch` | Backfills enrollments, switches to `running`. |',
    '',
    'Dry-run any flow payload with `POST /v1/campaigns/{id}/flow:validate` before writing.',
    '',
    '## End-to-end walkthrough',
    '',
    'Replace `{base_url}` and `{api_key}` with your Client API base URL and account API key (`Authorization: Bearer f_...`).',
    '',
    '### 1. Create a draft campaign',
    '',
    '```bash',
    `curl -sS -X POST '{base_url}/v1/campaigns' \\`,
    `  -H 'Authorization: Bearer {api_key}' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample({
      name: 'Q2 Outbound',
      sending_interval_seconds: 1800,
      mailbox_ids: [EXAMPLE_MAILBOX_ID],
      tag_ids: [EXAMPLE_TAG_ID],
    }),
    '\'',
    '```',
    '',
    'Response (`201`):',
    '',
    '```json',
    jsonExample({
      data: {
        id: EXAMPLE_CAMPAIGN_ID,
        name: 'Q2 Outbound',
        status: 'draft',
        source: 'manual',
        flow_data: { nodes: [], edges: [] },
        created_at: '2026-07-06T18:00:00.000Z',
      },
    }),
    '```',
    '',
    '### 2. Save the flow',
    '',
    '```bash',
    `curl -sS -X PUT '{base_url}/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/flow' \\`,
    `  -H 'Authorization: Bearer {api_key}' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample(CAMPAIGN_FLOW_EXAMPLE_LINEAR),
    '\'',
    '```',
    '',
    'Response (`200`):',
    '',
    '```json',
    jsonExample({
      data: CAMPAIGN_FLOW_EXAMPLE_LINEAR,
    }),
    '```',
    '',
    'Furnace returns the **normalized** flow — variant labels may be re-lettered (`A`, `B`, …) and wait nodes may have `wait_duration_seconds` derived from `duration` + `unit`.',
    '',
    '### 3. Upload a lead',
    '',
    '```bash',
    `curl -sS -X POST '{base_url}/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/leads' \\`,
    `  -H 'Authorization: Bearer {api_key}' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample({
      email: 'alex@acme.com',
      first_name: 'Alex',
      last_name: 'Rivera',
      custom_lead_data: { company: 'Acme Corp' },
    }),
    '\'',
    '```',
    '',
    'Response (`201`):',
    '',
    '```json',
    jsonExample({
      data: {
        id: 'b2c3d4e5-f6a7-4890-b123-456789abcdef',
        campaign_id: EXAMPLE_CAMPAIGN_ID,
        email: 'alex@acme.com',
        first_name: 'Alex',
        custom_lead_data: { company: 'Acme Corp' },
        created: true,
      },
    }),
    '```',
    '',
    '### 4. Validate before launch (optional)',
    '',
    '```bash',
    `curl -sS -X POST '{base_url}/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/flow:validate' \\`,
    `  -H 'Authorization: Bearer {api_key}' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'',
    jsonExample(CAMPAIGN_FLOW_EXAMPLE_LINEAR),
    '\'',
    '```',
    '',
    'Response (`200`):',
    '',
    '```json',
    jsonExample({
      data: {
        normalized_flow: CAMPAIGN_FLOW_EXAMPLE_LINEAR,
        allowed: true,
        change_kind: 'none',
        change_reasons: [],
        lifecycle: { allowed: true },
        issues: [],
      },
    }),
    '```',
    '',
    '### 5. Launch',
    '',
    'Launch requires: campaign **name**, a saved **flow**, and at least one **mailbox** assigned.',
    '',
    '```bash',
    `curl -sS -X POST '{base_url}/v1/campaigns/${EXAMPLE_CAMPAIGN_ID}/launch' \\`,
    `  -H 'Authorization: Bearer {api_key}' \\`,
    `  -H 'Content-Type: application/json' \\`,
    '  -d \'{}\'',
    '```',
    '',
    'Response (`200`):',
    '',
    '```json',
    jsonExample({
      data: { id: EXAMPLE_CAMPAIGN_ID, status: 'running' },
    }),
    '```',
    '',
    '## Lifecycle',
    '',
    '| Status | Flow topology | Copy / config edits |',
    '| --- | --- | --- |',
    '| `draft` | Fully editable (add/remove nodes, rewire edges, delete variants) | Allowed |',
    '| `running` | Structural edits return `flow_locked` — pause in the builder first | Allowed (subject, body, wait duration, add variant, toggle active, positions, lead source fields, categorizer config) |',
    '| `paused` | Fully editable (flow saves reactivate completed leads on non-categorizer nodes with a live next step) | Allowed |',
    '| `stopped` | Locked — all flow edits return `flow_locked` | Blocked |',
    '',
    'Flow saves return `reactivated_count` when completed enrollments are parked on a non-categorizer node that still has an outgoing edge to a node present in the flow: those enrollments are set back to `active` so they continue into the next steps after resume. Categorizer category-exit completions are not reactivated.',
    '',
    '## Draft vs live lock',
    '',
    '| Change | Draft | Running | Paused | Stopped |',
    '| --- | --- | --- | --- | --- |',
    '| Add/remove node | Allowed | Blocked (`flow_locked`) | Allowed | Blocked |',
    '| Rewire / add / remove edge | Allowed | Blocked | Allowed | Blocked |',
    '| Delete or replace variant id | Allowed | Blocked | Allowed | Blocked |',
    '| Edit subject/body/html | Allowed | Allowed | Allowed | Blocked |',
    '| Add variant / toggle active | Allowed | Allowed | Allowed | Blocked |',
    '| Edit wait duration / categorizer config / node position | Allowed | Allowed | Allowed | Blocked |',
    '| Lead source field keys / import mapping | Allowed | Allowed | Allowed | Blocked |',
    '',
    'Structural changes are detected by comparing the stored flow to your payload. When blocked, `change_kind` is `structural` and `change_reasons` includes one or more of:',
    '',
    '- `node_added`',
    '- `node_removed`',
    '- `node_type_changed`',
    '- `edge_added_or_rewired`',
    '- `edge_removed_or_rewired`',
    '- `variant_removed_or_replaced`',
    '',
    'Blocked response (`403`):',
    '',
    '```json',
    jsonExample({
      error: {
        type: 'permission_error',
        code: 'flow_locked',
        message: 'Pause the campaign to add or rearrange steps.',
      },
    }),
    '```',
    '',
    `Validation failures (\`400\`) return \`invalid_flow\` with a \`details[]\` array of \`{ path, code, message }\` objects. See **Models → ${modelLink('FlowValidationIssue')}** for the full error-code catalog.`,
    '',
    '## Example flow: email -> wait -> email',
    '',
    '```json',
    jsonExample(CAMPAIGN_FLOW_EXAMPLE_LINEAR),
    '```',
    '',
    '## Example flow: categorizer branch',
    '',
    '```json',
    jsonExample(CAMPAIGN_FLOW_EXAMPLE_CATEGORIZER),
    '```',
    '',
    '## Lead imports depend on flow fields',
    '',
    'When the `leadSource` node declares `customFieldKeys`, every lead create or bulk-import payload must include those keys inside `custom_lead_data`. Use `GET /v1/campaigns/{id}/lead-fields` to inspect the current requirements.',
    '',
    '## Troubleshooting',
    '',
    '| Symptom | Likely cause | Fix |',
    '| --- | --- | --- |',
    `| \`400 invalid_flow\` with \`details[]\` | Validation failed on launch-phase validate or non-draft write | Draft saves return warnings in \`validation.warnings\`; check \`launch_state.blocking_issues\` before launch |`,
    '| `403 flow_locked` on `PUT .../flow` | Structural edit on a running campaign, or any edit on stopped | Pause the campaign for structural changes; stopped campaigns cannot be edited |',
    '| `400` on launch | Missing name, empty flow, or no mailbox | Set name, save flow, assign `mailbox_ids` on create or `PATCH /v1/campaigns/{id}` |',
    '| Lead import missing custom field | `customFieldKeys` on lead source not satisfied | Include every key in `custom_lead_data`; check `GET .../lead-fields` |',
    '| `unknown_merge_variable` in launch readiness | Token used in email copy but not declared on lead source | Add key to `customFieldKeys` or `mappedStandardFieldKeys`, or remove token from copy |',
    '| `unreachable_node` | Orphan node not connected from lead source | Add edges so every node is reachable from `leadSource` |',
    '| `cycle_detected` | Edge creates a loop | Remove the cycle; flows must be DAGs |',
  ].join('\n');
}
