export function buildChangelogMarkdown(): string {
  return [
    'Version numbers match `info.version` on this API.',
    '',
    'Breaking changes increment the major version. Additive endpoints and fields increment minor. Patch is reserved for documentation-only or non-contract fixes.',
    '',
    '---',
    '',
    '## 1.2.0',
    '',
    '**Inbox expansion** — triage, outbound messaging, and ops endpoints for programmatic inbox use.',
    '',
    '### Added',
    '',
    '- **Webhooks** guide in `/docs` (Guide → Webhooks) with example payloads for every outbound event type',
    '- Consolidated `/docs` into a single Scalar document with Guide and API sidebar sections',
    '',
    '**Thread list & triage**',
    '',
    '- `GET /v1/threads` — new query params: `q`, `unread_only`, `conversation_status`, `category` (`no_category` for uncategorized), `tag_ids`, `date_from`, `date_to`, `has_reply_only` (default `true`)',
    '- `PATCH /v1/threads/{id}` — partial update: `category`, `conversation_status`, `read`',
    '',
    '**Outbound messaging**',
    '',
    '- `POST /v1/threads/{id}/forward` — queue forward job (`forward_message_id` required)',
    '- `GET /v1/message-jobs/{id}` — poll reply/forward job status',
    '- `POST /v1/message-jobs/{id}/cancel` — cancel queued/failed outbound job',
    '- `POST /v1/message-jobs/{id}/send-now` — expedite queued outbound job',
    '',
    '**Inbox ops**',
    '',
    '- `PUT /v1/threads/{id}/out-of-office` — set OOO (`resume_mode`: `scheduled` | `instant` | `none`)',
    '- `DELETE /v1/threads/{id}/out-of-office` — clear OOO',
    '- `POST /v1/threads/{id}/replace-lead` — replace thread lead; optional `forward_message_id`',
    '- `GET /v1/thread-tags` — list account thread tags',
    '- `POST /v1/threads/{id}/tags:add` / `tags:remove` — assign or remove tag on thread',
    '',
    '### Changed',
    '',
    '- `POST /v1/threads/{id}/reply` — optional `in_reply_to_message_id` (defaults to latest message)',
    '',
    '### Notes',
    '',
    '- Poll outbound sends with `/v1/message-jobs/{id}`, not `/v1/jobs/{id}` (import jobs only).',
    '- Tag create/edit/delete remains in the Furnace app; the API supports list + assign/remove only.',
    '',
    '---',
    '',
    '## 1.1.0',
    '',
    '**People, lists, jobs, and batch webhooks**',
    '',
    '### Added',
    '',
    '- `GET/PATCH /v1/people`, `GET/PATCH /v1/people/{globalLeadId}`',
    '- `GET/POST/PATCH/DELETE /v1/lead-lists`, list membership endpoints',
    '- `POST /v1/jobs`, `GET /v1/jobs/{id}` — async bulk operations',
    '- Campaign/mailbox tag CRUD and filtering',
    '- Sync bulk shortcuts: `leads:add`, `leads:remove`, `leads:remove-from-all-campaigns`, enrollment pause/resume',
    '- Batch completion webhooks (`*.completed`) for bulk and enrollment actions',
    '',
    '### Changed',
    '',
    '- Webhook allowlist: removed `enrollment.created` / `enrollment.updated`; added batch completion events',
    '',
    '---',
    '',
    '## 1.0.0',
    '',
    '**Initial Client API**',
    '',
    '### Added',
    '',
    '- Campaigns, leads, mailboxes, block list, campaign stats',
    '- Basic inbox: `GET /v1/threads`, `GET /v1/threads/{id}`, `GET /v1/threads/{id}/messages`, `POST /v1/threads/{id}/reply`',
    '- Atomic webhooks: `lead.*`, campaign lifecycle, `email.sent`, `reply.received`, `bounce.detected`',
    '- OpenAPI at `/openapi.json`, Scalar UI at `/docs`',
  ].join('\n');
}
