import {
  API_KEY_PREFIX,
  BULK_ASYNC_LIMIT,
  BULK_SYNC_LIMIT,
  DEFAULT_PAGE_SIZE,
  IDEMPOTENCY_TTL_HOURS,
  MAX_ASYNC_JOBS_PER_ACCOUNT,
  MAX_PAGE_SIZE,
  RATE_LIMIT_REQUESTS_PER_MINUTE,
} from './constants.js';
import { docsPublicPath, guideLink, modelLink, type DocLinkMode } from './docLinks.js';

/** Markdown body sections shared by intro MDX and contract tests. */
export function buildClientApiIntroMarkdown(): string {
  return [
    '## Business rules',
    '- Smartlead campaigns are read-only through this API.',
    '- Campaign flow topology is fully editable only while a campaign is in `draft` status.',
    '- Once a campaign is `running`, `paused`, or `stopped`, structural flow changes return `403 permission_error` with code `flow_locked`.',
    `- Sync bulk imports accept up to ${BULK_SYNC_LIMIT} leads per request.`,
    `- Async bulk imports accept up to ${BULK_ASYNC_LIMIT} leads per request and allow at most ${MAX_ASYNC_JOBS_PER_ACCOUNT} queued/running jobs per account.`,
    '- When a campaign defines custom lead fields, every key must be present in `custom_lead_data` on create and bulk import requests.',
    '',
    '## Inbox message jobs',
    '- Reply and forward endpoints return `202` with a `message_job` id.',
    '- Poll outbound send status with `GET /v1/message-jobs/{id}`. Do not use `GET /v1/jobs/{id}` — that endpoint is for async import jobs only.',
    '- Cancel or expedite queued sends with `POST /v1/message-jobs/{id}/cancel` and `POST /v1/message-jobs/{id}/send-now`.',
    '- Update thread triage state with `PATCH /v1/threads/{id}` (`category`, `conversation_status`, `read`).',
  ].join('\n');
}

/** Fumadocs MDX home page (hero, cards, reference sections). */
export function buildClientApiIntroMdx(linkMode: DocLinkMode = 'docs'): string {
  const details = buildClientApiIntroMarkdown();
  // Raw <a> tags in MDX bypass the Next.js Link wrapper, so they need public /docs paths.
  const quickstartHref = docsPublicPath('/guides/campaign-quickstart/');
  const referenceHref = docsPublicPath('/reference/');
  return [
    '<div className="doc-hero not-prose">',
    '',
    '<p className="doc-hero__tagline">',
    'Account-scoped REST API for campaigns, leads, people, saved lists, inbox, mailboxes, and more.',
    '</p>',
    '',
    '<div className="doc-hero__actions">',
    `<a className="primary" href="${quickstartHref}">Campaign quickstart</a>`,
    `<a className="secondary" href="${referenceHref}">API Reference</a>`,
    '</div>',
    '',
    '</div>',
    '',
    `New to the API? Start with ${guideLink('Campaign quickstart', '/guides/campaign-quickstart/', linkMode)}. Flow schemas such as ${modelLink('CampaignFlow', linkMode)} and ${modelLink('FlowUpdate', linkMode)} are in the ${guideLink('API Reference', '/reference/', linkMode)}.`,
    '',
    '<CardGroup cols={2}>',
    '',
    `<Card title="Authentication" icon="gear">`,
    '',
    `Send your account API key as \`Authorization: Bearer ${API_KEY_PREFIX}...\`. Keys are created in Furnace Account Settings. Revoked, expired, or unknown keys return \`401 authentication_error\`.`,
    '',
    '</Card>',
    '',
    `<Card title="Rate limits" icon="plug">`,
    '',
    `Responses include \`X-RateLimit-Limit\`, \`X-RateLimit-Remaining\`, and \`X-RateLimit-Reset\`. Furnace allows ${RATE_LIMIT_REQUESTS_PER_MINUTE} requests per account per minute.`,
    '',
    '</Card>',
    '',
    `<Card title="Pagination" icon="book">`,
    '',
    `List endpoints return \`{ data, limit, offset, total_count }\`. Default page size is ${DEFAULT_PAGE_SIZE}; maximum is ${MAX_PAGE_SIZE}.`,
    '',
    '</Card>',
    '',
    `<Card title="Errors" icon="terminal">`,
    '',
    'Errors use `{ error: { type, code, message, param? } }`. See the table below for HTTP status codes and typical causes.',
    '',
    '</Card>',
    '',
    '</CardGroup>',
    '',
    '## Account scope',
    'Every `/v1/*` resource is limited to the account that owns the API key. Requests never cross account boundaries.',
    '',
    '## Idempotency',
    `Use the \`Idempotency-Key\` header on \`POST /v1/campaigns/{id}/leads\` and \`POST /v1/campaigns/{id}/leads/bulk\` to safely retry imports. Furnace replays the cached response for matching account, route, key, and request-body hash for ${IDEMPOTENCY_TTL_HOURS} hours.`,
    '',
    '## Error reference',
    '',
    '| HTTP | type | Typical causes |',
    '| --- | --- | --- |',
    '| 400 | `invalid_request_error` | Invalid JSON, missing parameters, bad status transitions, missing custom fields |',
    '| 401 | `authentication_error` | Missing, invalid, revoked, or expired API key |',
    '| 403 | `permission_error` | Smartlead campaign mutation, deleted campaign, admin-only operation |',
    '| 404 | `invalid_request_error` | Campaign, lead, mailbox, thread, message job, or import job not found in this account |',
    '| 429 | `rate_limit_error` | Too many requests or too many concurrent async import jobs |',
    '| 500 | `api_error` | Unhandled server-side error |',
    '',
    details,
  ].join('\n');
}
