export {
  buildFurnaceEmail,
  buildFurnaceEmailText,
  buildBodyParagraph,
  buildSectionHeading,
  buildDataTable,
  escapeHtml,
  FURNACE_EMAIL_BRAND,
  type FurnaceEmailOptions,
  type FurnaceEmailTextOptions,
} from './buildFurnaceEmail.js';

export {
  buildTeamInvitationEmail,
  buildPlatformInviteEmail,
  buildAccountAmendmentEmail,
  buildHelpMessageEmail,
  buildFluxQuizSubmissionEmail,
  buildConfirmSignupEmail,
  buildMagicLinkEmail,
  buildResetPasswordEmail,
  buildInviteUserEmail,
  buildChangeEmailEmail,
  buildReauthenticationEmail,
  buildPasswordChangedEmail,
  buildEmailAddressChangedEmail,
  buildSupabaseAuthTemplates,
  SUPABASE_AUTH_PLACEHOLDERS,
  type TransactionalEmail,
  type FluxQuizAnswerRow,
} from './presets/index.js';
